### ISSUE TITLE
Name change issue

### ISSUE THREAD

**Issue by jackolney** [dide-tools/didehpc#32]
In master, this exists:`didehpc::didewin_config_global`

But just noticed that in the linux dev branch its all been corrected – so this issue may be moot.

**Comment by richfitz** [comment]
yeah, once the bugs get shaken out and I push this to everyone it will all resolve.  Pete is testing the new version and I'll get OJ on it tomorrow.  If you want to give it a bash, please do (but be aware of the issues in the [porting guide](https://github.com/dide-tools/didehpc/blob/develop/porting_guide.md))

Current "active" branch is `develop`, not `linux_support`

**Comment by richfitz** [comment]
Actually, where do you see this: didehpc::didewin_config_global ?

**Comment by jackolney** [comment]
https://github.com/dide-tools/didehpc/blob/master/R/config.R#L234

**Comment by richfitz** [comment]
Oh good, that will never come out as `didehpc::didewin_config_global` because when the package got renamed in be27372520070987e2d9fe58e6ec33d34ed48f1f that was changed.  My muscle memory though keeps typing `didewin` so I'm constantly removing typo bugs
